'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Corrections

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vwDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwDefault As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''litStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlDateSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDateSeries As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlWorkbooks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWorkbooks As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlDistributions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDistributions As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CompareValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator1 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''RequiredFieldValidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtMOR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMOR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vwEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwEdit As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''P1Row1Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row1Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row1Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row1Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row1Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row1Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row1Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row1Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row2Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row2Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row2Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row2Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row2Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row2Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row2Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row2Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row3Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row3Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row3Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row3Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row3Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row3Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row3Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row3Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row4Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row4Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row4Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row4Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row4Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row4Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row4Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row4Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row5Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row5Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row5Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row5Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row5Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row5Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row5Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row5Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row6Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row6Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row6Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row6Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row6Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row6Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row6Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row6Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row7Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row7Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row7Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row7Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row7Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row7Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row7Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row7Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row8Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row8Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row8Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row8Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row8Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row8Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row8Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row8Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row9Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row9Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row9Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row9Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row9Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row9Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row9Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row9Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row10Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row10Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row10Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row10Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row10Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row10Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row10Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row10Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row11Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row11Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row11Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row11Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row11Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row11Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row11Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row11Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row12Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row12Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row12Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row12Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row12Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row12Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row12Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row12Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row13Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row13Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row13Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row13Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row13Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row13Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row13Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row13Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row14Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row14Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row14Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row14Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row14Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row14Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row14Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row14Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row15Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row15Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row15Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row15Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row15Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row15Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row15Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row15Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row16Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row16Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row16Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row16Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row16Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row16Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row16Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row16Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row17Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row17Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row17Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row17Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row17Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row17Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row18Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row18Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row18Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row18Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row18Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row18Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row19Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row19Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row19Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row19Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row19Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row19Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row20Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row20Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row20Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row20Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row20Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row20Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row21Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row21Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row21Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row21Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row21Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row21Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row22Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row22Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row22Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row22Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row22Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row22Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row23Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row23Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row23Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row23Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row23Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row23Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row24Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row24Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row24Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row24Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row24COl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row24COl3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row25Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row25Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row25Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row25Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row25Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row25Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row26Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row26Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row26Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row26Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row26Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row26Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row27Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row27Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row27Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row27Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row27Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row27Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row28Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row28Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row28Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row28Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row28Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row28Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row29Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row29Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row29Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row29Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row29Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row29Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row30Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row30Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row30Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row30Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row30Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row30Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row31Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row31Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row31Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row31Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row31Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row31Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row32Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row32Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row32Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row32Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P1Row32Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1Row32Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vwEdit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwEdit2 As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''P2Row1Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P2Row1Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P2Row2Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P2Row2Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P2Row3Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P2Row3Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P2Row4Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P2Row4Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P2Row5Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P2Row5Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpdate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vwNotAuthorized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwNotAuthorized As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''NotAuthorized1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotAuthorized1 As Global.SalesSurveysApplication.NotAuthorized

    '''<summary>
    '''vwError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwError As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ErrorMessage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorMessage1 As Global.SalesSurveysApplication.ErrorMessage
End Class
