'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class DataEditForm

    '''<summary>
    '''litPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPageTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vwChooseSurveySeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwChooseSurveySeries As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ddlSurveySeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSurveySeries As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnGoToEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoToEdit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vwEditData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwEditData As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''litSectionTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSectionTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Row1Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row1Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row1Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row1Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row1Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row1Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row1Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row1Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row1Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row1Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row1Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row1Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row1Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row1Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row2Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row2Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row2Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row2Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row2Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row2Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row2Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row2Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row2Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row2Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row2Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row2Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row2Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row2Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row3Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row3Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row3Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row3Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row3Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row3Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row3Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row3Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row3Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row3Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row3Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row3Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row3Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row3Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row4Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row4Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row4Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row4Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row4Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row4Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row4Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row4Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row4Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row4Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row4Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row4Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row4Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row4Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row5Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row5Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row5Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row5Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row5Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row5Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row5Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row5Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row5Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row5Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row5Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row5Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row5Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row5Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row6Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row6Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row6Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row6Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row6Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row6Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row6Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row6Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row6Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row6Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row6Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row6Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row6Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row6Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row7Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row7Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row7Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row7Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row7Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row7Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row7Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row7Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row7Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row7Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row7Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row7Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row7Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row7Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row8Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row8Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row8Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row8Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row8Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row8Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row8Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row8Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row8Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row8Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row8Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row8Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row8Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row8Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row9Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row9Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row9Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row9Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row9Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row9Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row9Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row9Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row9Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row9Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row9Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row9Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row9Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row9Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row10Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row10Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row10Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row10Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row10Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row10Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row10Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row10Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row10Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row10Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row10Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row10Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row10Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row10Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row11Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row11Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row11Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row11Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row11Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row11Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row11Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row11Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row11Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row11Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row11Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row11Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row11Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row11Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row12Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row12Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row12Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row12Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row12Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row12Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row12Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row12Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row12Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row12Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row13Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row13Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row13Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row13Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row13Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row13Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row13Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row13Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row13Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row13Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row14Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row14Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row14Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row14Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row14Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row14Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row14Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row14Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row14Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row14Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row15Col1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row15Col1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row15Col2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row15Col2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row15Col3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row15Col3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row15Col4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row15Col4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row15Col5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row15Col5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row15Col6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row15Col6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Row15Col7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Row15Col7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vwError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwError As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ErrorMessage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorMessage1 As Global.SalesSurveysApplication.ErrorMessage

    '''<summary>
    '''vwNotAuthorized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwNotAuthorized As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''NotAuthorized1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotAuthorized1 As Global.SalesSurveysApplication.NotAuthorized
End Class
